//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCompanySale
    {
        public Nullable<long> ID { get; set; }
        public string ProductCategory { get; set; }
        public string ProductSubCategory { get; set; }
        public Nullable<int> OrderYear { get; set; }
        public string OrderQtr { get; set; }
        public Nullable<decimal> Sales { get; set; }
    }
}
