//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureWorks.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductCatalog
    {
        public Nullable<long> ID { get; set; }
        public int ProductID { get; set; }
        public string ProductNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductModel { get; set; }
        public string ProductCategory { get; set; }
        public string ProductSubcategory { get; set; }
        public string Description { get; set; }
        public string CultureID { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public decimal ListPrice { get; set; }
    }
}
